# ─── Pashu Sentinel — Seeded Demo Data ───────────────────────────────────────
# Deterministic dataset. Primary case: COW-1024, Khandala village, Junnar Taluk.
# ~25 cases clustered around the primary outbreak for map demo.

from datetime import datetime, timedelta, timezone

# Reference timestamp (fixed so demo is always reproducible)
REF_TS = datetime(2026, 9, 10, 8, 30, 0, tzinfo=timezone.utc)


def _ts(offset_hours: float) -> str:
    return (REF_TS + timedelta(hours=offset_hours)).isoformat()


SEEDED_CASES = [
    # ── Primary outbreak case ────────────────────────────────────────────
    {
        "id": "COW-1024",
        "species": "Cattle",
        "breed": "Gir",
        "age_years": 4,
        "tag_id": "COW-1024",
        "village": "Khandala",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7831,
        "lng": 73.9286,
        "symptoms": ["fever", "oral vesicles", "excessive salivation", "lameness"],
        "mortality": 1,
        "reported_by": "FIELD-007",
        "assigned_vet": "VET-001",
        "status": "RISK_ANALYZED",
        "risk_factors": {"clinical": 92, "vaccination": 80, "environmental": 85, "spatial": 95},
        "reported_at": _ts(0),
        "updated_at": _ts(1.5),
        "notes": "Owner reports 3 more animals showing similar symptoms. Vaccination record incomplete.",
    },

    # ── Cluster cases (within protection zone, ~0–3 km) ─────────────────
    {
        "id": "COW-1025",
        "species": "Cattle",
        "breed": "Khillari",
        "age_years": 6,
        "tag_id": "COW-1025",
        "village": "Khandala",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7860,
        "lng": 73.9310,
        "symptoms": ["fever", "oral vesicles"],
        "mortality": 0,
        "reported_by": "FIELD-007",
        "assigned_vet": "VET-001",
        "status": "REPORTED",
        "risk_factors": {"clinical": 78, "vaccination": 70, "environmental": 82, "spatial": 93},
        "reported_at": _ts(2),
        "updated_at": _ts(2),
        "notes": "",
    },
    {
        "id": "GOAT-0310",
        "species": "Goat",
        "breed": "Osmanabadi",
        "age_years": 2,
        "tag_id": "GOAT-0310",
        "village": "Khandala",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7812,
        "lng": 73.9255,
        "symptoms": ["fever", "lameness"],
        "mortality": 0,
        "reported_by": "FIELD-007",
        "assigned_vet": "VET-002",
        "status": "UNDER_INVESTIGATION",
        "risk_factors": {"clinical": 68, "vaccination": 55, "environmental": 80, "spatial": 91},
        "reported_at": _ts(-5),
        "updated_at": _ts(1),
        "notes": "",
    },
    {
        "id": "COW-1026",
        "species": "Cattle",
        "breed": "HF Cross",
        "age_years": 3,
        "tag_id": "COW-1026",
        "village": "Khandala",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7845,
        "lng": 73.9298,
        "symptoms": ["excessive salivation", "oral vesicles"],
        "mortality": 0,
        "reported_by": "FIELD-008",
        "assigned_vet": "VET-001",
        "status": "LAB_TESTING",
        "risk_factors": {"clinical": 74, "vaccination": 65, "environmental": 83, "spatial": 94},
        "reported_at": _ts(-10),
        "updated_at": _ts(-1),
        "notes": "Swab sample collected. Awaiting FMD PCR result.",
    },
    {
        "id": "SHP-0088",
        "species": "Sheep",
        "breed": "Deccani",
        "age_years": 1,
        "tag_id": "SHP-0088",
        "village": "Khandala",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7800,
        "lng": 73.9270,
        "symptoms": ["fever", "lameness"],
        "mortality": 0,
        "reported_by": "FIELD-009",
        "assigned_vet": "VET-003",
        "status": "REPORTED",
        "risk_factors": {"clinical": 58, "vaccination": 50, "environmental": 78, "spatial": 90},
        "reported_at": _ts(3),
        "updated_at": _ts(3),
        "notes": "",
    },

    # ── Surveillance zone cases (~3–10 km) ───────────────────────────────
    {
        "id": "COW-0899",
        "species": "Cattle",
        "breed": "Sahiwal",
        "age_years": 7,
        "tag_id": "COW-0899",
        "village": "Narayangaon",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8150,
        "lng": 73.9850,
        "symptoms": ["fever"],
        "mortality": 0,
        "reported_by": "FIELD-010",
        "assigned_vet": "VET-002",
        "status": "REPORTED",
        "risk_factors": {"clinical": 42, "vaccination": 75, "environmental": 60, "spatial": 70},
        "reported_at": _ts(-24),
        "updated_at": _ts(-24),
        "notes": "",
    },
    {
        "id": "GOAT-0311",
        "species": "Goat",
        "breed": "Osmanabadi",
        "age_years": 3,
        "tag_id": "GOAT-0311",
        "village": "Ale",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7550,
        "lng": 73.8900,
        "symptoms": ["cough", "nasal discharge"],
        "mortality": 0,
        "reported_by": "FIELD-011",
        "assigned_vet": "VET-003",
        "status": "UNDER_INVESTIGATION",
        "risk_factors": {"clinical": 48, "vaccination": 60, "environmental": 55, "spatial": 65},
        "reported_at": _ts(-36),
        "updated_at": _ts(-12),
        "notes": "",
    },
    {
        "id": "COW-1010",
        "species": "Cattle",
        "breed": "Gir",
        "age_years": 5,
        "tag_id": "COW-1010",
        "village": "Wadaj",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7900,
        "lng": 74.0100,
        "symptoms": ["fever", "reduced milk"],
        "mortality": 0,
        "reported_by": "FIELD-012",
        "assigned_vet": "VET-004",
        "status": "LAB_CONFIRMED",
        "risk_factors": {"clinical": 65, "vaccination": 45, "environmental": 72, "spatial": 75},
        "reported_at": _ts(-48),
        "updated_at": _ts(-6),
        "notes": "Confirmed FMD serotype O. Alert issued.",
    },
    {
        "id": "BUF-0205",
        "species": "Buffalo",
        "breed": "Murrah",
        "age_years": 8,
        "tag_id": "BUF-0205",
        "village": "Rajuri",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.7650,
        "lng": 73.9600,
        "symptoms": ["oral vesicles", "lameness"],
        "mortality": 1,
        "reported_by": "FIELD-013",
        "assigned_vet": "VET-001",
        "status": "ALERT_SENT",
        "risk_factors": {"clinical": 82, "vaccination": 40, "environmental": 88, "spatial": 87},
        "reported_at": _ts(-72),
        "updated_at": _ts(-2),
        "notes": "High-risk case. Movement restriction imposed.",
    },
    {
        "id": "COW-1030",
        "species": "Cattle",
        "breed": "Jersey Cross",
        "age_years": 4,
        "tag_id": "COW-1030",
        "village": "Otur",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8300,
        "lng": 73.9400,
        "symptoms": ["fever"],
        "mortality": 0,
        "reported_by": "FIELD-014",
        "assigned_vet": "VET-005",
        "status": "RISK_ANALYZED",
        "risk_factors": {"clinical": 55, "vaccination": 72, "environmental": 58, "spatial": 68},
        "reported_at": _ts(-18),
        "updated_at": _ts(-10),
        "notes": "",
    },

    # ── Outer / background cases (beyond 10 km) ──────────────────────────
    {
        "id": "COW-0750",
        "species": "Cattle",
        "breed": "Khillari",
        "age_years": 9,
        "tag_id": "COW-0750",
        "village": "Ambegaon",
        "taluk": "Ambegaon",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8600,
        "lng": 73.8500,
        "symptoms": ["reduced milk", "lethargy"],
        "mortality": 0,
        "reported_by": "FIELD-015",
        "assigned_vet": "VET-004",
        "status": "REPORTED",
        "risk_factors": {"clinical": 35, "vaccination": 80, "environmental": 40, "spatial": 30},
        "reported_at": _ts(-96),
        "updated_at": _ts(-96),
        "notes": "",
    },
    {
        "id": "GOAT-0220",
        "species": "Goat",
        "breed": "Sangamneri",
        "age_years": 2,
        "tag_id": "GOAT-0220",
        "village": "Manchar",
        "taluk": "Ambegaon",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8400,
        "lng": 73.8100,
        "symptoms": ["cough"],
        "mortality": 0,
        "reported_by": "FIELD-016",
        "assigned_vet": "VET-005",
        "status": "CONTAINMENT",
        "risk_factors": {"clinical": 30, "vaccination": 85, "environmental": 35, "spatial": 25},
        "reported_at": _ts(-120),
        "updated_at": _ts(-48),
        "notes": "Resolved. Containment measures lifted.",
    },
    {
        "id": "COW-0920",
        "species": "Cattle",
        "breed": "HF Cross",
        "age_years": 5,
        "tag_id": "COW-0920",
        "village": "Shirur",
        "taluk": "Shirur",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8000,
        "lng": 74.3500,
        "symptoms": ["fever", "diarrhoea"],
        "mortality": 0,
        "reported_by": "FIELD-017",
        "assigned_vet": "VET-004",
        "status": "LAB_TESTING",
        "risk_factors": {"clinical": 60, "vaccination": 55, "environmental": 65, "spatial": 45},
        "reported_at": _ts(-60),
        "updated_at": _ts(-20),
        "notes": "",
    },
    {
        "id": "BUF-0310",
        "species": "Buffalo",
        "breed": "Surti",
        "age_years": 6,
        "tag_id": "BUF-0310",
        "village": "Baramati",
        "taluk": "Baramati",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.1520,
        "lng": 74.5820,
        "symptoms": ["mastitis", "reduced milk"],
        "mortality": 0,
        "reported_by": "FIELD-018",
        "assigned_vet": "VET-003",
        "status": "UNDER_INVESTIGATION",
        "risk_factors": {"clinical": 45, "vaccination": 60, "environmental": 50, "spatial": 35},
        "reported_at": _ts(-80),
        "updated_at": _ts(-40),
        "notes": "",
    },
    {
        "id": "COW-0444",
        "species": "Cattle",
        "breed": "Gir",
        "age_years": 3,
        "tag_id": "COW-0444",
        "village": "Indapur",
        "taluk": "Indapur",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 17.9600,
        "lng": 75.0200,
        "symptoms": ["fever", "reduced milk", "nasal discharge"],
        "mortality": 0,
        "reported_by": "FIELD-019",
        "assigned_vet": "VET-002",
        "status": "REPORTED",
        "risk_factors": {"clinical": 52, "vaccination": 65, "environmental": 48, "spatial": 40},
        "reported_at": _ts(-108),
        "updated_at": _ts(-108),
        "notes": "",
    },
    {
        "id": "SHP-0110",
        "species": "Sheep",
        "breed": "Deccani",
        "age_years": 2,
        "tag_id": "SHP-0110",
        "village": "Purandar",
        "taluk": "Purandar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.2800,
        "lng": 74.0200,
        "symptoms": ["cough", "nasal discharge"],
        "mortality": 0,
        "reported_by": "FIELD-020",
        "assigned_vet": "VET-005",
        "status": "RISK_ANALYZED",
        "risk_factors": {"clinical": 38, "vaccination": 70, "environmental": 42, "spatial": 30},
        "reported_at": _ts(-144),
        "updated_at": _ts(-90),
        "notes": "",
    },
    {
        "id": "COW-1055",
        "species": "Cattle",
        "breed": "Sahiwal",
        "age_years": 6,
        "tag_id": "COW-1055",
        "village": "Bhor",
        "taluk": "Bhor",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.1500,
        "lng": 73.8500,
        "symptoms": ["fever", "lethargy"],
        "mortality": 0,
        "reported_by": "FIELD-021",
        "assigned_vet": "VET-001",
        "status": "CONTAINMENT",
        "risk_factors": {"clinical": 40, "vaccination": 78, "environmental": 45, "spatial": 32},
        "reported_at": _ts(-200),
        "updated_at": _ts(-72),
        "notes": "Resolved. Animal recovering.",
    },
    {
        "id": "GOAT-0415",
        "species": "Goat",
        "breed": "Osmanabadi",
        "age_years": 1,
        "tag_id": "GOAT-0415",
        "village": "Mulshi",
        "taluk": "Mulshi",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.5200,
        "lng": 73.5100,
        "symptoms": ["diarrhoea", "lethargy"],
        "mortality": 0,
        "reported_by": "FIELD-022",
        "assigned_vet": "VET-003",
        "status": "REPORTED",
        "risk_factors": {"clinical": 33, "vaccination": 60, "environmental": 38, "spatial": 28},
        "reported_at": _ts(-168),
        "updated_at": _ts(-168),
        "notes": "",
    },
    {
        "id": "COW-0780",
        "species": "Cattle",
        "breed": "Khillari",
        "age_years": 8,
        "tag_id": "COW-0780",
        "village": "Mawal",
        "taluk": "Mawal",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.6200,
        "lng": 73.5800,
        "symptoms": ["fever", "lameness"],
        "mortality": 0,
        "reported_by": "FIELD-023",
        "assigned_vet": "VET-002",
        "status": "UNDER_INVESTIGATION",
        "risk_factors": {"clinical": 62, "vaccination": 50, "environmental": 65, "spatial": 55},
        "reported_at": _ts(-90),
        "updated_at": _ts(-30),
        "notes": "",
    },
    {
        "id": "BUF-0188",
        "species": "Buffalo",
        "breed": "Murrah",
        "age_years": 5,
        "tag_id": "BUF-0188",
        "village": "Velhe",
        "taluk": "Velhe",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.2700,
        "lng": 73.6500,
        "symptoms": ["oral vesicles", "excessive salivation"],
        "mortality": 0,
        "reported_by": "FIELD-024",
        "assigned_vet": "VET-004",
        "status": "LAB_TESTING",
        "risk_factors": {"clinical": 72, "vaccination": 42, "environmental": 68, "spatial": 62},
        "reported_at": _ts(-55),
        "updated_at": _ts(-15),
        "notes": "Possible FMD. Swab sample sent to IVRI.",
    },
    {
        "id": "COW-0555",
        "species": "Cattle",
        "breed": "Jersey Cross",
        "age_years": 4,
        "tag_id": "COW-0555",
        "village": "Daund",
        "taluk": "Daund",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.4600,
        "lng": 74.5800,
        "symptoms": ["reduced milk", "fever"],
        "mortality": 0,
        "reported_by": "FIELD-025",
        "assigned_vet": "VET-005",
        "status": "RISK_ANALYZED",
        "risk_factors": {"clinical": 50, "vaccination": 68, "environmental": 52, "spatial": 40},
        "reported_at": _ts(-130),
        "updated_at": _ts(-80),
        "notes": "",
    },
    {
        "id": "SHP-0055",
        "species": "Sheep",
        "breed": "Deccani",
        "age_years": 3,
        "tag_id": "SHP-0055",
        "village": "Panshet",
        "taluk": "Velhe",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.3500,
        "lng": 73.7200,
        "symptoms": ["cough"],
        "mortality": 0,
        "reported_by": "FIELD-026",
        "assigned_vet": "VET-003",
        "status": "REPORTED",
        "risk_factors": {"clinical": 28, "vaccination": 75, "environmental": 30, "spatial": 22},
        "reported_at": _ts(-180),
        "updated_at": _ts(-180),
        "notes": "",
    },
    {
        "id": "COW-1100",
        "species": "Cattle",
        "breed": "Gir",
        "age_years": 5,
        "tag_id": "COW-1100",
        "village": "Junnar",
        "taluk": "Junnar",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 19.2000,
        "lng": 73.8900,
        "symptoms": ["fever", "nasal discharge"],
        "mortality": 0,
        "reported_by": "FIELD-027",
        "assigned_vet": "VET-001",
        "status": "UNDER_INVESTIGATION",
        "risk_factors": {"clinical": 55, "vaccination": 60, "environmental": 58, "spatial": 48},
        "reported_at": _ts(-50),
        "updated_at": _ts(-25),
        "notes": "",
    },
    {
        "id": "BUF-0400",
        "species": "Buffalo",
        "breed": "Surti",
        "age_years": 7,
        "tag_id": "BUF-0400",
        "village": "Haveli",
        "taluk": "Haveli",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.5900,
        "lng": 73.9600,
        "symptoms": ["mastitis"],
        "mortality": 0,
        "reported_by": "FIELD-028",
        "assigned_vet": "VET-002",
        "status": "REPORTED",
        "risk_factors": {"clinical": 32, "vaccination": 70, "environmental": 38, "spatial": 28},
        "reported_at": _ts(-220),
        "updated_at": _ts(-220),
        "notes": "",
    },
    {
        "id": "COW-0630",
        "species": "Cattle",
        "breed": "Sahiwal",
        "age_years": 6,
        "tag_id": "COW-0630",
        "village": "Khed",
        "taluk": "Khed",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.8500,
        "lng": 73.8600,
        "symptoms": ["fever", "oral vesicles", "lameness"],
        "mortality": 1,
        "reported_by": "FIELD-029",
        "assigned_vet": "VET-004",
        "status": "ALERT_SENT",
        "risk_factors": {"clinical": 85, "vaccination": 35, "environmental": 80, "spatial": 78},
        "reported_at": _ts(-40),
        "updated_at": _ts(-5),
        "notes": "High-risk. Alerting district officer.",
    },
]
