// ─── pashuDB.js ───────────────────────────────────────────────────────────────
// Single Dexie (IndexedDB) database instance shared across the entire app.
//
// ref.md §15 — Offline-First Architecture:
//   "Dexie.js wraps IndexedDB with a clean promise-based API for structured,
//    durable, async local storage that survives tab closures and app reloads."
//
// Schema (v1):
//   cases   — one row per case; primary key = id (CASE-XXXX / animal tag)
//   reports — one row per queued field report; primary key = reportId (UUID)
//
// Both tables are indexed for fast reactive queries (useLiveQuery).
// ─────────────────────────────────────────────────────────────────────────────

import Dexie from 'dexie'

// ─── Database definition ──────────────────────────────────────────────────────
export const pashuDB = new Dexie('PashuSentinelDB')

pashuDB.version(1).stores({
  // cases table
  //   Primary key:  id           (e.g. 'CASE-1042')
  //   Indices:      status, species, district, taluk  — for filtered queries
  //                 [lat+lng]   — compound index for geo queries
  //                 reportedAt  — for time-sorted views
  cases: 'id, status, species, district, taluk, reportedAt',

  // reports table — offline field-report queue
  //   Primary key:  reportId     (UUID generated by the frontend)
  //   Indices:      syncStatus  — quickly find PENDING / FAILED reports to sync
  //                 createdAt   — chronological ordering
  reports: 'reportId, syncStatus, createdAt',
})

// ─── Versioning note ─────────────────────────────────────────────────────────
// To add columns or indices in future, add:
//   pashuDB.version(2).stores({ cases: 'id, status, ...new_index' }).upgrade(tx => {...})
// Dexie handles migration automatically.
